url = """ 
    smkn9malang.sch.id/profil-sekolah/sejarah/,
    https://smkn9malang.sch.id/profil-sekolah/visi-misi/,
    https://smkn9malang.sch.id/profil-sekolah/sasaran-mutu/,
    https://smkn9malang.sch.id/profil-sekolah/tujuan/,
    https://smkn9malang.sch.id/profil-sekolah/struktur-organisasi/,
    https://smkn9malang.sch.id/profil-sekolah/sarana-prasarana/,
    https://smkn9malang.sch.id/profil-sekolah/peta-sekolah/,
    https://smkn9malang.sch.id/program-keahlian/teknik-sepeda-motor-tsm/,
    https://smkn9malang.sch.id/program-keahlian/teknik-komputer-jaringan/,
    https://smkn9malang.sch.id/program-keahlian/rekayasa-perangkat-lunak/,
    https://smkn9malang.sch.id/alumni-rpl/,
    https://smkn9malang.sch.id/alumni-rpl/,
    https://smkn9malang.sch.id/program-keahlian-elektronika-industri-elind/,

    https://smkn9malang.sch.id/program-unggulan/axioo-class-program/,
    https://smkn9malang.sch.id/program-unggulan/oracle-academy/,
    https://smkn9malang.sch.id/program-unggulan/program-mikrotik-academy/,
    https://smkn9malang.sch.id/program-unggulan/kampung-animasi/,
    https://smkn9malang.sch.id/category/prestasi-siswa/,
    https://smkn9malang.sch.id/bursa-kerja-khusus-bkk/,
    https://smkn9malang.sch.id/program-unggulan/lembaga-sertifikasi-profesi/,
    https://smkn9malang.sch.id/unit-produksi/,
    """